package com.fpcs.invt.mgmt.sys.domain;
// default package
// Generated 17 Jun, 2017 6:07:24 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustCrDrDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cust_cr_dr_details", schema = "shop_data")
public class CustCrDrDetails implements java.io.Serializable {

	private long custCrDrDetailsId;
	private CustDetails custDetails;
	private BigDecimal custCrAmount;
	private BigDecimal custDrAmount;
	private BigDecimal custCurBalance;
	private String custRemarks;

	public CustCrDrDetails() {
	}

	public CustCrDrDetails(long custCrDrDetailsId) {
		this.custCrDrDetailsId = custCrDrDetailsId;
	}

	public CustCrDrDetails(long custCrDrDetailsId, CustDetails custDetails, BigDecimal custCrAmount,
			BigDecimal custDrAmount, BigDecimal custCurBalance, String custRemarks) {
		this.custCrDrDetailsId = custCrDrDetailsId;
		this.custDetails = custDetails;
		this.custCrAmount = custCrAmount;
		this.custDrAmount = custDrAmount;
		this.custCurBalance = custCurBalance;
		this.custRemarks = custRemarks;
	}

	@Id

	@Column(name = "cust_cr_dr_details_id", unique = true, nullable = false)
	public long getCustCrDrDetailsId() {
		return this.custCrDrDetailsId;
	}

	public void setCustCrDrDetailsId(long custCrDrDetailsId) {
		this.custCrDrDetailsId = custCrDrDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_acc_no")
	public CustDetails getCustDetails() {
		return this.custDetails;
	}

	public void setCustDetails(CustDetails custDetails) {
		this.custDetails = custDetails;
	}

	@Column(name = "cust_cr_amount", precision = 131089, scale = 0)
	public BigDecimal getCustCrAmount() {
		return this.custCrAmount;
	}

	public void setCustCrAmount(BigDecimal custCrAmount) {
		this.custCrAmount = custCrAmount;
	}

	@Column(name = "cust_dr_amount", precision = 131089, scale = 0)
	public BigDecimal getCustDrAmount() {
		return this.custDrAmount;
	}

	public void setCustDrAmount(BigDecimal custDrAmount) {
		this.custDrAmount = custDrAmount;
	}

	@Column(name = "cust_cur_balance", precision = 131089, scale = 0)
	public BigDecimal getCustCurBalance() {
		return this.custCurBalance;
	}

	public void setCustCurBalance(BigDecimal custCurBalance) {
		this.custCurBalance = custCurBalance;
	}

	@Column(name = "cust_remarks", length = 300)
	public String getCustRemarks() {
		return this.custRemarks;
	}

	public void setCustRemarks(String custRemarks) {
		this.custRemarks = custRemarks;
	}

}
