package com.fpcs.invt.mgmt.sys.domain;
// default package
// Generated 18 Jun, 2017 12:27:41 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "roles", schema = "user_data")
public class Roles implements java.io.Serializable {

	private long roleId;
	private String role;
	private Set<UserLogin> userLogins = new HashSet<>(0);

	public Roles() {
	}

	public Roles(long roleId) {
		this.roleId = roleId;
	}

	public Roles(long roleId, String role, Set<UserLogin> userLogins) {
		this.roleId = roleId;
		this.role = role;
		this.userLogins = userLogins;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UserLogin> getUserLogins() {
		return this.userLogins;
	}

	public void setUserLogins(Set<UserLogin> userLogins) {
		this.userLogins = userLogins;
	}

}
