package com.fpcs.invt.mgmt.sys.domain;
// default package

// Generated 17 Jun, 2017 6:07:24 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fpcs.invt.mgmt.sys.constants.SchemaDetails;

/**
 * ShopDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "shop_details", schema = "shop_data")
public class ShopDetails implements java.io.Serializable {

	private long shopId;
	private String shopName;
	private String shopLicenceNo;
	private String addressLine1;
	private String addressLine2;
	private String town;
	private Long pincode;
	private String city;
	private String state;
	private String country;
	private String shopOwner;
	private Set<AvailableStock> availableStocks = new HashSet<>(0);
	private Set<Stock> stocks = new HashSet<>(0);
	private Set<CustDetails> custDetailses = new HashSet<>(0);
	private Set<UserLogin> userLogins = new HashSet<>(0);

	public ShopDetails() {
	}

	public ShopDetails(long shopId) {
		this.shopId = shopId;
	}

	public ShopDetails(long shopId, String shopName, String shopLicenceNo, String addressLine1, String addressLine2,
			String town,Long pincode, String city, String state, String country, String shopOwner,
			Set<AvailableStock> availableStocks, Set<Stock> stocks, Set<CustDetails> custDetailses,
			Set<UserLogin> userLogins) {
		this.shopId = shopId;
		this.shopName = shopName;
		this.shopLicenceNo = shopLicenceNo;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.town = town;
		this.pincode = pincode;
		this.city = city;
		this.state = state;
		this.country = country;
		this.shopOwner = shopOwner;
		this.availableStocks = availableStocks;
		this.stocks = stocks;
		this.custDetailses = custDetailses;
		this.userLogins = userLogins;
	}

	@Id
	@SequenceGenerator(allocationSize = SchemaDetails.DEFLT_ALLOC_SIZE , name = SchemaDetails.SEQ_SHOP_ID_NAME , sequenceName = SchemaDetails.DB_SEQ_SHOP_ID_NAME , schema = SchemaDetails.SHOP_DATA)
	@GeneratedValue(strategy = GenerationType.SEQUENCE , generator = SchemaDetails.SEQ_SHOP_ID_NAME)
	@Column(name = "shop_id", unique = true, nullable = false)
	public long getShopId() {
		return this.shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "shop_name", length = 300)
	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	@Column(name = "shop_licence_no", length = 20)
	public String getShopLicenceNo() {
		return this.shopLicenceNo;
	}

	public void setShopLicenceNo(String shopLicenceNo) {
		this.shopLicenceNo = shopLicenceNo;
	}

	@Column(name = "address_line_1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line_2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "town", length = 30)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}
	
	@Column(name = "pincode")
	public Long getPincode() {
		return pincode;
	}

	public void setPincode(Long pincode) {
		this.pincode = pincode;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "shop_owner", length = 30)
	public String getShopOwner() {
		return this.shopOwner;
	}

	public void setShopOwner(String shopOwner) {
		this.shopOwner = shopOwner;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopDetails")
	public Set<AvailableStock> getAvailableStocks() {
		return this.availableStocks;
	}

	public void setAvailableStocks(Set<AvailableStock> availableStocks) {
		this.availableStocks = availableStocks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopDetails")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopDetails")
	public Set<CustDetails> getCustDetailses() {
		return this.custDetailses;
	}

	public void setCustDetailses(Set<CustDetails> custDetailses) {
		this.custDetailses = custDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopDetails")
	public Set<UserLogin> getUserLogins() {
		return this.userLogins;
	}

	public void setUserLogins(Set<UserLogin> userLogins) {
		this.userLogins = userLogins;
	}

}
