package com.fpcs.invt.mgmt.sys.domain;
// default package
// Generated 17 Jun, 2017 6:07:24 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "stock", schema = "shop_data")
public class Stock implements java.io.Serializable {

	private StockId id;
	private ShopDetails shopDetails;
	private Set<AvailableStock> availableStocks = new HashSet<>(0);

	public Stock() {
	}

	public Stock(StockId id) {
		this.id = id;
	}

	public Stock(StockId id, ShopDetails shopDetails, Set<AvailableStock> availableStocks) {
		this.id = id;
		this.shopDetails = shopDetails;
		this.availableStocks = availableStocks;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "itemName", column = @Column(name = "item_name", nullable = false, length = 300)),
			@AttributeOverride(name = "itemCode", column = @Column(name = "item_code", nullable = false, length = 15)) })
	public StockId getId() {
		return this.id;
	}

	public void setId(StockId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public ShopDetails getShopDetails() {
		return this.shopDetails;
	}

	public void setShopDetails(ShopDetails shopDetails) {
		this.shopDetails = shopDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<AvailableStock> getAvailableStocks() {
		return this.availableStocks;
	}

	public void setAvailableStocks(Set<AvailableStock> availableStocks) {
		this.availableStocks = availableStocks;
	}

}
