package com.fpcs.invt.mgmt.sys.domain.static_data;
// default package
// Generated Jun 25, 2017 4:27:52 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "country", schema = "static_data")
public class Country implements java.io.Serializable {

	private String country;
	private Date deletedOn;
	private Set<State> states = new HashSet<>(0);
	private Set<City> cities = new HashSet<>(0);

	public Country() {
	}

	public Country(String country) {
		this.country = country;
	}

	public Country(String country, Date deletedOn, Set<State> states, Set<City> cities) {
		this.country = country;
		this.deletedOn = deletedOn;
		this.states = states;
		this.cities = cities;
	}

	@Id

	@Column(name = "country", unique = true, nullable = false, length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_on", length = 13)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
