package com.fpcs.invt.mgmt.sys.domain.static_data;
// default package
// Generated Jun 25, 2017 4:27:52 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * State generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "state", schema = "static_data", uniqueConstraints = { @UniqueConstraint(columnNames = "country")})
public class State implements java.io.Serializable {

	private StateId id;
	private Country country;
	private Date deletedOn;
	private Set<City> cities = new HashSet<>(0);

	public State() {
	}

	public State(StateId id, Country country) {
		this.id = id;
		this.country = country;
	}

	public State(StateId id, Country country, Date deletedOn, Set<City> cities) {
		this.id = id;
		this.country = country;
		this.deletedOn = deletedOn;
		this.cities = cities;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "state", column = @Column(name = "state", unique = true, nullable = false, length = 50)),
			@AttributeOverride(name = "country", column = @Column(name = "country", unique = true, nullable = false, length = 50)) })
	public StateId getId() {
		return this.id;
	}

	public void setId(StateId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country", unique = true, nullable = false, insertable = false, updatable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_on", length = 13)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
