package com.fpcs.invt.mgmt.sys.domain.user_data;
// default package
// Generated Jun 25, 2017 4:27:52 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MenuItemAccess generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "menu_item_access", schema = "user_data")
public class MenuItemAccess implements java.io.Serializable {

	private long menuItemAccessId;
	private Long shopId;
	private String role;
	private String menuItem;
	private Date deletedOn;

	public MenuItemAccess() {
	}

	public MenuItemAccess(long menuItemAccessId) {
		this.menuItemAccessId = menuItemAccessId;
	}

	public MenuItemAccess(long menuItemAccessId, Long shopId, String role, String menuItem, Date deletedOn) {
		this.menuItemAccessId = menuItemAccessId;
		this.shopId = shopId;
		this.role = role;
		this.menuItem = menuItem;
		this.deletedOn = deletedOn;
	}

	@Id

	@Column(name = "menu_item_access_id", unique = true, nullable = false)
	public long getMenuItemAccessId() {
		return this.menuItemAccessId;
	}

	public void setMenuItemAccessId(long menuItemAccessId) {
		this.menuItemAccessId = menuItemAccessId;
	}

	@Column(name = "shop_id")
	public Long getShopId() {
		return this.shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "menu_item")
	public String getMenuItem() {
		return this.menuItem;
	}

	public void setMenuItem(String menuItem) {
		this.menuItem = menuItem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 29)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

}
