package com.fpcs.invt.mgmt.sys.domain.user_data;
// default package
// Generated Jun 25, 2017 4:27:52 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Roles generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "roles", schema = "user_data")
public class Roles implements java.io.Serializable {

	private long roleId;
	private String role;
	private Date deletedOn;
	private Set<UserLogin> userLogins = new HashSet<>(0);

	public Roles() {
	}

	public Roles(long roleId) {
		this.roleId = roleId;
	}

	public Roles(long roleId, String role, Date deletedOn, Set<UserLogin> userLogins) {
		this.roleId = roleId;
		this.role = role;
		this.deletedOn = deletedOn;
		this.userLogins = userLogins;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_on", length = 13)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UserLogin> getUserLogins() {
		return this.userLogins;
	}

	public void setUserLogins(Set<UserLogin> userLogins) {
		this.userLogins = userLogins;
	}

}
