package com.fpcs.invt.mgmt.sys.domain.shop_data;
// default package
// Generated Jun 25, 2017 4:35:15 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AvailableStock generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "available_stock", schema = "shop_data")
public class AvailableStock implements java.io.Serializable {

	private long itemId;
	private ShopDetails shopDetails;
	private Stock stock;
	private Long itemQty;
	private BigDecimal itemPrice;
	private Date deletedOn;

	public AvailableStock() {
	}

	public AvailableStock(long itemId) {
		this.itemId = itemId;
	}

	public AvailableStock(long itemId, ShopDetails shopDetails, Stock stock, Long itemQty, BigDecimal itemPrice,
			Date deletedOn) {
		this.itemId = itemId;
		this.shopDetails = shopDetails;
		this.stock = stock;
		this.itemQty = itemQty;
		this.itemPrice = itemPrice;
		this.deletedOn = deletedOn;
	}

	@Id

	@Column(name = "item_id", unique = true, nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public ShopDetails getShopDetails() {
		return this.shopDetails;
	}

	public void setShopDetails(ShopDetails shopDetails) {
		this.shopDetails = shopDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "item_name", referencedColumnName = "item_name"),
			@JoinColumn(name = "item_code", referencedColumnName = "item_code") })
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Column(name = "item_qty")
	public Long getItemQty() {
		return this.itemQty;
	}

	public void setItemQty(Long itemQty) {
		this.itemQty = itemQty;
	}

	@Column(name = "item_price", precision = 131089, scale = 0)
	public BigDecimal getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_on", length = 13)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

}
