package com.fpcs.invt.mgmt.sys.domain.shop_data;
// default package
// Generated Jun 25, 2017 4:35:15 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cust_details", schema = "shop_data")
public class CustDetails implements java.io.Serializable {

	private long custAccNo;
	private ShopDetails shopDetails;
	private String custFirstName;
	private String custMiddleName;
	private String custLastName;
	private BigDecimal totalBalance;
	private String addressLine1;
	private String addressLine2;
	private String town;
	private String city;
	private String state;
	private String country;
	private Date deletedOn;
	private Set<CustCrDrDetails> custCrDrDetailses = new HashSet<>(0);

	public CustDetails() {
	}

	public CustDetails(long custAccNo) {
		this.custAccNo = custAccNo;
	}

	public CustDetails(long custAccNo, ShopDetails shopDetails, String custFirstName, String custMiddleName,
			String custLastName, BigDecimal totalBalance, String addressLine1, String addressLine2, String town,
			String city, String state, String country, Date deletedOn, Set<CustCrDrDetails> custCrDrDetailses) {
		this.custAccNo = custAccNo;
		this.shopDetails = shopDetails;
		this.custFirstName = custFirstName;
		this.custMiddleName = custMiddleName;
		this.custLastName = custLastName;
		this.totalBalance = totalBalance;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.town = town;
		this.city = city;
		this.state = state;
		this.country = country;
		this.deletedOn = deletedOn;
		this.custCrDrDetailses = custCrDrDetailses;
	}

	@Id

	@Column(name = "cust_acc_no", unique = true, nullable = false)
	public long getCustAccNo() {
		return this.custAccNo;
	}

	public void setCustAccNo(long custAccNo) {
		this.custAccNo = custAccNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public ShopDetails getShopDetails() {
		return this.shopDetails;
	}

	public void setShopDetails(ShopDetails shopDetails) {
		this.shopDetails = shopDetails;
	}

	@Column(name = "cust_first_name", length = 300)
	public String getCustFirstName() {
		return this.custFirstName;
	}

	public void setCustFirstName(String custFirstName) {
		this.custFirstName = custFirstName;
	}

	@Column(name = "cust_middle_name", length = 300)
	public String getCustMiddleName() {
		return this.custMiddleName;
	}

	public void setCustMiddleName(String custMiddleName) {
		this.custMiddleName = custMiddleName;
	}

	@Column(name = "cust_last_name", length = 300)
	public String getCustLastName() {
		return this.custLastName;
	}

	public void setCustLastName(String custLastName) {
		this.custLastName = custLastName;
	}

	@Column(name = "total_balance", precision = 131089, scale = 0)
	public BigDecimal getTotalBalance() {
		return this.totalBalance;
	}

	public void setTotalBalance(BigDecimal totalBalance) {
		this.totalBalance = totalBalance;
	}

	@Column(name = "address_line_1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line_2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "town", length = 30)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_on", length = 13)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "custDetails")
	public Set<CustCrDrDetails> getCustCrDrDetailses() {
		return this.custCrDrDetailses;
	}

	public void setCustCrDrDetailses(Set<CustCrDrDetails> custCrDrDetailses) {
		this.custCrDrDetailses = custCrDrDetailses;
	}

}
